### PR TITLE
fix: only add connections that can be authenticated

### LINKED ISSUE #400: Cannot create a new Connection
I cannot create a new connection

### Steps
1. Launch VSCode without the `cli` config mode
2. Click `+` icon in `InfluxDB` pane to create a new connection.
3. Fill in details
4. Click `save`

### Expected results

The connection is created or and error is reported

### Actual results

Nothing happens and there is no feedback. Additionally clicking `test` doesn't do anything either.

### Env

VSCode Info:
Version: 1.66.2
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:49:24.808Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Linux x64 5.17.4-arch1-1

VSFlux: v1.0.4

### PR DESCRIPTION
**Pull request by rockstar**
In the current plugin, when one tries to add a connection that either
has bad auth information or a bad network connection, the "save"
functionality has no feedback. Making a connection to the database is
important, as that's how we get the org id, which is needed for a few of
the requests we make.

This patch removes the "Test" functionality, as it is now unneeded, and
prevents adding databases with bad auth information.

Fixes #400

### CODE REVIEW

File: src/controllers/AddInstanceController.ts [hunk 1]
```diff
@@ -116,14 +116,18 @@ async function convertMessageToInstance(
...
+            const orgsAPI = new APIClient(instance).getOrgsApi()
+            const organizations = await orgsAPI.getOrgs({ org: instance.org })
+            if (!organizations || !organizations.orgs || !organizations.orgs.length || organizations.orgs[0].id === undefined) {
+                console.error(`No organization named "${instance.org}" found!`)
+            } else {
+                instance.orgID = organizations.orgs[0].id
+            }
         }
+    } catch (e) {
+        console.error(e)
```
Comment (appletreeisyellow) [inline src/controllers/AddInstanceController.ts:130]: nice
