### PR TITLE
fix(query): fix table return

### LINKED ISSUE #106: table view should returns an array of results
Current table result of an influx query returns 1 table. We should allow a query returns multiple tables.

### PR DESCRIPTION
**Pull request by kelwang**
unit tested and manual tested

close #106

### CODE REVIEW

File: src/components/Client.ts [hunk 1]
```diff
@@ -94,7 +97,7 @@ export class Client {
     }
 
     this.cli = new CLI({ 'disable-folding': true })
-    this.cli.on('log', console.debug)
```
Comment (bthesorceror) [inline src/components/Client.ts]: this need to be un commented
